import { NextResponse, type NextRequest } from "next/server";
import { TSRAutoGenerationService } from '@/lib/tsr-auto-generation-service';

export async function GET(
  request: NextRequest,
  { params }: { params: { trfId: string } },
) {
  try {
    // Properly await params to fix the Next.js warning
    const { trfId } = await Promise.resolve(params);
    console.log(`API_TRF_AUTO_GEN_GET_START: Fetching auto-generated requests for TSR ${trfId}.`);

    const autoGeneratedRequests = await TSRAutoGenerationService.getAutoGeneratedRequests(trfId);

    console.log(`API_TRF_AUTO_GEN_GET: Found ${autoGeneratedRequests.transportRequests.length} transport requests and ${autoGeneratedRequests.accommodationRequests.length} accommodation requests for TSR ${trfId}`);

    return NextResponse.json({
      tsrId: trfId,
      autoGenerated: autoGeneratedRequests
    });
  } catch (error: any) {
    console.error(
      `API_TRF_AUTO_GEN_GET_ERROR for TSR ${params?.trfId}:`,
      error.message,
      error.stack,
    );
    return NextResponse.json(
      {
        error: `Failed to fetch auto-generated requests.`,
        details: {
          message: error.message || "Unknown error",
          errorType: error.name || "Error",
        },
      },
      { status: 500 },
    );
  }
}